### ISSUE TITLE
Sounds are not working

### ISSUE THREAD

**Issue by MilianDevOps** [gallowaylabs/streamdeck-tomato-timer#2]
Neither default sounds nor custom sounds work

**Comment by mgway** [comment]
Sounds seem to be working on my machine, so could you provide a few more details such as:

- What operating system are you using?
- What Stream Deck software version do you have?
- What version of TomatoTimer are you using? This can be found by right clicking on the Timer activity in the list of all activities in the Stream Deck configuration UI
- Do other Stream Deck sounds work? The built-in Play Audio activity can be used to test this
- Does the sound not play correctly when clicking the "click to play" preview button, when the time expires, or both?
