### ISSUE TITLE
Add ability to reset timers and move on

### ISSUE THREAD

**Issue by garethhowell** [gallowaylabs/streamdeck-tomato-timer#3]
Nice app, but being able to reset or cancel a timer would be nice.

**Comment by mgway** [comment]
Do you mean being able to skip or reset a single phase, e.g. go back to the beginning of the current work phase? That's an interesting idea, I'll have to think of a way to trigger all of those actions with just one button.

**Comment by bkarstaedt** [comment]
I absolutely agree with @garethhowell.

Skipping to the next phase or totally resetting by a long button press would be a great feature.

**Comment by mgway** [comment]
Apologies for the lengthy wait, but I've implemented this in v0.5.0 which is now available on the releases page (or wait a few days for the release to be approved by Elgato and receive the update automatically). 

Pressing and holding the button for 2 seconds in any state will advance the timer to the next phase.

**Comment by garethhowell** [comment]
Good job. It works!

**Comment by mgway** [comment]
v0.5.0 is in the Streamdeck plugin store now
