### ISSUE TITLE
Enhancement Request: Time position

### ISSUE THREAD

**Issue by Fluxell** [gallowaylabs/streamdeck-tomato-timer#4]
At the angle my StreamDeck sits, the time at the bottom is distorted by the edge of the button cover. It would be nice to be able to position the time at the top of the bottom.

**Comment by mgway** [comment]
The time remaining counter uses the `title` property that is included with all buttons. You can adjust the location, font, size, and color of the counter using the 'T' dropdown next to the title field
![image](https://user-images.githubusercontent.com/556514/226487370-c36d41e8-01c7-4e09-a4e8-5ca0bab470bf.png)

However, the end of the timer circle is a bit difficult to see if the title is set to the top of the button in this manner, so I'll add an option to switch where the circle starts/ends at in the next release.

**Comment by mgway** [comment]
Relocating the time circle start/end location is now available in v0.5.0
