### ISSUE TITLE
Feature Request: Repeat alarm sound

### ISSUE THREAD

**Issue by maparaschivei** [gallowaylabs/streamdeck-tomato-timer#7]
Hello,

Thank you for this very useful Stream Deck plugin.

I humbly request adding an on/off option to 'repeat' the custom alarm sounds until the next phase is started.

Most often I use the break times to get up and walk away from my desk. Having the option to repeat the alarm sounds will help make sure I don't miss the alarms.

Thank you!

**Comment by maparaschivei** [comment]
FYI, decided to help contribute to this project by creating a PR with the requested feature. 👍

**Comment by mgway** [comment]
I've submitted the updated plugin to the Stream Deck store. It usually takes a day for it to be approved and be pushed out as an automatic update, or you can download it from the releases page now. 

Thanks again
