### ISSUE TITLE
Just an FYI

### ISSUE THREAD

**Issue by Geekie2014** [gallowaylabs/streamdeck-tomato-timer#9]
Hey there, I'm Geekie from the BarRaider team, back when we first had the idea of making a Pomodoro timer (which we now have in the timer plugin) I looked into the trademarks for Pomodoro.

Just letting you guys know that the use of a Tomato in the icon is against Pomodoros trademark: https://francescocirillo.com/pages/pomodoro-trademark-guidelines
Just an heads up from someone who looked into it before :)!

**Comment by mgway** [comment]
Thanks for the heads up, I haven't changed the logo quite yet but I did add a disclaimer to the readme. 

While this is a pretty comprehensive trademark page, it doesn't seem like they're doing [a](https://www.tomatotimers.com/) [particularly](https://pomofocus.io/) [rigorous](https://www.toptal.com/project-managers/tomato-timer) [job](https://studywithme.io/aesthetic-pomodoro-timer/) [of ](https://pomodorotimer.online/) [enforcing](https://www.online-timers.com/pomodoro-timers) [that](https://apps.apple.com/us/app/pomodoro-focus-timer/id1265128036) [mark](https://play.google.com/store/apps/details?id=com.pomodrone.app&hl=en_US&gl=US).
